import type { ReactNode } from 'react';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { ThemeProvider } from 'next-themes';
import { SidebarProvider } from "../registry/new-york-v4/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import '@/app/globals.css';
import { Toaster } from '@/registry/new-york-v4/ui/sonner';
import { NavbarWrapper } from '@/components/navbar/navbar';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900'
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900'
});

export const metadata: Metadata = {
    title: 'nextjscodebook',
    description: 'Generated by create next app'
};

const Layout = ({ children }: Readonly<{ children: ReactNode }>) => {
    return (
        <html suppressHydrationWarning lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} bg-background text-foreground overscroll-none antialiased`}>
                <ThemeProvider attribute='class'>
                    <SidebarProvider>
                        <AppSidebar />
                        <main className='w-full'>
                            <NavbarWrapper/>
                            {children}
                        </main>
                        <Toaster />
                    </SidebarProvider>
                </ThemeProvider>
            </body>
        </html>
    );
};

export default Layout;
